Repository solun-pm/solun, pull requests merged in 2023-06, with the labels that each got.

#29 Added Domain Variable
  .env.local
  app/api/file/upload/route.ts
  app/api/message/create/route.ts
  app/file/page.tsx
  app/layout.tsx
  app/msg/page.tsx
  package-lock.json
  package.json
Labels: enhancement

#30 Changed more variables env
  .env.local
  .env.sample
  components/CTABanner.tsx
  components/header.tsx
  components/services.tsx
  components/welcomer.tsx
Labels: enhancement

#31 Create docker-image.yml
  .github/workflows/docker-image.yml
Labels: enhancement

#32 Added Logo URL
  app/layout.tsx
Labels: bug

#33 Changed ENVs
  app/api/file/upload/route.ts
  app/api/message/create/route.ts
  app/file/page.tsx
  app/layout.tsx
  app/msg/page.tsx
  docker-compose.yml
  next.config.js
Labels: bug

#34 Update
  app/api/message/create/route.ts
  next.config.js
  utils/dbConn.ts
Labels: bug

#36 Db and URL changes
  app/file/[...data]/page.tsx
  app/layout.tsx
  utils/dbConn.ts
Labels: bug

#42 Minor Improvements
  app/api/file/delete/route.ts
  app/file/[...data]/page.tsx
  app/layout.tsx
  app/msg/[...data]/page.tsx
  package-lock.json
  package.json
Labels: enhancement

#45 Switched msg/file password to new hashing method
  app/api/file/decrypt/route.ts
  app/api/file/receive/route.ts
  app/api/file/upload/route.ts
  app/api/message/create/route.ts
  app/api/message/receive/route.ts
  package-lock.json
  package.json
  public/solun-logo.png
  utils/hash.ts
Labels: bug, enhancement

#47 Added UI Changes
  app/file/[...data]/page.tsx
  app/file/page.tsx
  app/msg/page.tsx
Labels: enhancement

#51 Added Terms of Service
  app/tos/page.tsx
  components/footer.tsx
  content/tos.mdx
Labels: documentation, enhancement

#54 Added information text about child abuse prevention
  content/howFile.mdx
Labels: documentation, enhancement

#56 Optimized SEO
  app/file/[...data]/layout.tsx
  app/file/[...data]/page.tsx
  app/file/layout.tsx
  app/file/page.tsx
  app/how-file/page.tsx
  app/how-message/page.tsx
  app/layout.tsx
  app/msg/[...data]/layout.tsx
  app/msg/[...data]/page.tsx
  app/msg/layout.tsx
  app/msg/page.tsx
  app/not-found.tsx
  app/page.tsx
  app/privacy/page.tsx
  app/tos/page.tsx
  robots.txt
Labels: enhancement

#59 Changed Error Handling and Compatibility for /file
  app/api/file/decrypt/route.ts
  app/api/file/delete/route.ts
  app/api/file/download/route.ts
  app/api/file/receive/route.ts
  app/api/message/create/route.ts
  app/file/[...data]/page.tsx
  app/file/page.tsx
  app/msg/[...data]/page.tsx
  app/msg/page.tsx
  package-lock.json
  package.json
Labels: bug, enhancement

#65 Updated files - and .env
  .env.local
  app/api/file/upload/route.ts
  app/api/message/create/route.ts
  app/file/[...data]/layout.tsx
  app/file/layout.tsx
  app/layout.tsx
  app/msg/[...data]/layout.tsx
  app/msg/layout.tsx
  components/CTABanner.tsx
  components/header.tsx
  components/services.tsx
  components/welcomer.tsx
Labels: bug, enhancement

#66 Moved Sitemap
  public/sitemap.xml
Labels: enhancement

#68 Fixed UI bug @ /file
  app/file/[...data]/page.tsx
Labels: bug

#69 Minor spelling mistakes
  app/file/[...data]/layout.tsx
  app/msg/[...data]/layout.tsx
Labels: bug

#70 Switched all Solun Server & Client Functions to the Solun Packages
  .env.local
  Dockerfile
  app/api/file/check/route.ts
  app/api/file/delete/route.ts
  app/api/file/download/route.ts
  app/api/file/receive/route.ts
  app/api/file/upload/route.ts
  app/api/message/check/route.ts
  app/api/message/create/route.ts
  app/api/message/delete/route.ts
  app/api/message/receive/route.ts
  app/file/[...data]/layout.tsx
  app/file/page.tsx
  app/msg/[...data]/layout.tsx
  app/msg/page.tsx
  docker-compose.yml
  package-lock.json
  package.json
  utils/clientEncryption.ts
  utils/dbConn.ts
  utils/dbUtils.ts
  utils/encryption.ts
  utils/generateAES.ts
  utils/generateIV.ts
  utils/generateId.ts
  utils/generatePassword.ts
  utils/hash.ts
Labels: enhancement

#71 Moved API routes to api.solun.pm
  app/api/file/check/route.ts
  app/api/file/receive/route.ts
  app/api/message/check/route.ts
  app/api/message/create/route.ts
  app/api/message/delete/route.ts
  app/api/message/receive/route.ts
  app/file/[...data]/page.tsx
  app/msg/[...data]/page.tsx
  app/msg/page.tsx
Labels: enhancement

#73 Switched File Download, Upload, Delete to new Solun API
  app/api/file/delete/route.ts
  app/api/file/download/route.ts
  app/api/file/upload/route.ts
  app/file/[...data]/page.tsx
  app/file/page.tsx
  models/file.ts
  models/message.ts
Labels: enhancement

#74 Password Generation
  app/file/page.tsx
  app/msg/page.tsx
Labels: bug

#76 Updated and Show Version
  app/not-found.tsx
  app/page.tsx
  components/footer.tsx
  package-lock.json
  package.json
Labels: enhancement

#77 Added better client side message and file pwd encryption
  app/file/page.tsx
  app/msg/[...data]/page.tsx
  app/msg/page.tsx
  package-lock.json
  package.json
Labels: bug, enhancement

#78 quick fix
  app/msg/page.tsx
  package-lock.json
  package.json
Labels: bug, enhancement

#79 Fixed error on file and msg and made it more secure
  .github/workflows/docker-image.yml
  app/file/page.tsx
  app/msg/[...data]/page.tsx
  app/msg/page.tsx
  package-lock.json
  package.json
  public/robots.txt
Labels: bug, enhancement
